// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect CaseLotCelebrity_Roo_ToString {
    
    public String CaseLotCelebrity.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Enable: ").append(getEnable()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("LastModifyTime: ").append(getLastModifyTime()).append(", ");
        sb.append("Lotno: ").append(getLotno()).append(", ");
        sb.append("Sortno: ").append(getSortno()).append(", ");
        sb.append("Userno: ").append(getUserno());
        return sb.toString();
    }
    
}
