// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.CaseLotCelebrity;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect CaseLotCelebrity_Roo_Json {
    
    public String CaseLotCelebrity.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static CaseLotCelebrity CaseLotCelebrity.fromJsonToCaseLotCelebrity(String json) {
        return new JSONDeserializer<CaseLotCelebrity>().use(null, CaseLotCelebrity.class).deserialize(json);
    }
    
    public static String CaseLotCelebrity.toJsonArray(Collection<CaseLotCelebrity> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<CaseLotCelebrity> CaseLotCelebrity.fromJsonArrayToCaseLotCelebritys(String json) {
        return new JSONDeserializer<List<CaseLotCelebrity>>().use(null, ArrayList.class).use("values", CaseLotCelebrity.class).deserialize(json);
    }
    
}
