// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.CaseLotCelebrity;
import java.lang.Long;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CaseLotCelebrity_Roo_Entity {
    
    declare @type: CaseLotCelebrity: @Entity;
    
    declare @type: CaseLotCelebrity: @Table(name = "CASELOTCELEBRITY");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager CaseLotCelebrity.entityManager;
    
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Long CaseLotCelebrity.id;
    
    public Long CaseLotCelebrity.getId() {
        return this.id;
    }
    
    public void CaseLotCelebrity.setId(Long id) {
        this.id = id;
    }
    
    @Transactional
    public void CaseLotCelebrity.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void CaseLotCelebrity.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            CaseLotCelebrity attached = CaseLotCelebrity.findCaseLotCelebrity(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void CaseLotCelebrity.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void CaseLotCelebrity.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public CaseLotCelebrity CaseLotCelebrity.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        CaseLotCelebrity merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager CaseLotCelebrity.entityManager() {
        EntityManager em = new CaseLotCelebrity().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long CaseLotCelebrity.countCaseLotCelebritys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM CaseLotCelebrity o", Long.class).getSingleResult();
    }
    
    public static List<CaseLotCelebrity> CaseLotCelebrity.findAllCaseLotCelebritys() {
        return entityManager().createQuery("SELECT o FROM CaseLotCelebrity o", CaseLotCelebrity.class).getResultList();
    }
    
    public static CaseLotCelebrity CaseLotCelebrity.findCaseLotCelebrity(Long id) {
        if (id == null) return null;
        return entityManager().find(CaseLotCelebrity.class, id);
    }
    
    public static List<CaseLotCelebrity> CaseLotCelebrity.findCaseLotCelebrityEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM CaseLotCelebrity o", CaseLotCelebrity.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
