// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.CaseLotBuy;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect CaseLotBuy_Roo_Json {
    
    public String CaseLotBuy.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static CaseLotBuy CaseLotBuy.fromJsonToCaseLotBuy(String json) {
        return new JSONDeserializer<CaseLotBuy>().use(null, CaseLotBuy.class).deserialize(json);
    }
    
    public static String CaseLotBuy.toJsonArray(Collection<CaseLotBuy> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<CaseLotBuy> CaseLotBuy.fromJsonArrayToCaseLotBuys(String json) {
        return new JSONDeserializer<List<CaseLotBuy>>().use(null, ArrayList.class).use("values", CaseLotBuy.class).deserialize(json);
    }
    
}
