// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.Integer;
import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect CaseLotBuy_Roo_JavaBean {
    
    public String CaseLotBuy.getCaselotId() {
        return this.caselotId;
    }
    
    public void CaseLotBuy.setCaselotId(String caselotId) {
        this.caselotId = caselotId;
    }
    
    public String CaseLotBuy.getUserno() {
        return this.userno;
    }
    
    public void CaseLotBuy.setUserno(String userno) {
        this.userno = userno;
    }
    
    public BigDecimal CaseLotBuy.getNum() {
        return this.num;
    }
    
    public void CaseLotBuy.setNum(BigDecimal num) {
        this.num = num;
    }
    
    public Date CaseLotBuy.getBuyTime() {
        return this.buyTime;
    }
    
    public void CaseLotBuy.setBuyTime(Date buyTime) {
        this.buyTime = buyTime;
    }
    
    public Integer CaseLotBuy.getFlag() {
        return this.flag;
    }
    
    public void CaseLotBuy.setFlag(Integer flag) {
        this.flag = flag;
    }
    
    public BigDecimal CaseLotBuy.getSafeAmt() {
        return this.safeAmt;
    }
    
    public void CaseLotBuy.setSafeAmt(BigDecimal safeAmt) {
        this.safeAmt = safeAmt;
    }
    
    public BigDecimal CaseLotBuy.getFreezeSafeAmt() {
        return this.freezeSafeAmt;
    }
    
    public void CaseLotBuy.setFreezeSafeAmt(BigDecimal freezeSafeAmt) {
        this.freezeSafeAmt = freezeSafeAmt;
    }
    
    public Integer CaseLotBuy.getBuyType() {
        return this.buyType;
    }
    
    public void CaseLotBuy.setBuyType(Integer buyType) {
        this.buyType = buyType;
    }
    
    public BigDecimal CaseLotBuy.getPrizeAmt() {
        return this.prizeAmt;
    }
    
    public void CaseLotBuy.setPrizeAmt(BigDecimal prizeAmt) {
        this.prizeAmt = prizeAmt;
    }
    
    public BigDecimal CaseLotBuy.getCommisionPrizeAmt() {
        return this.commisionPrizeAmt;
    }
    
    public void CaseLotBuy.setCommisionPrizeAmt(BigDecimal commisionPrizeAmt) {
        this.commisionPrizeAmt = commisionPrizeAmt;
    }
    
}
