// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.CaseLotBuy;
import java.lang.Integer;
import java.lang.String;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect CaseLotBuy_Roo_Finder {
    
    public static TypedQuery<CaseLotBuy> CaseLotBuy.findCaseLotBuysByCaselotId(String caselotId) {
        if (caselotId == null || caselotId.length() == 0) throw new IllegalArgumentException("The caselotId argument is required");
        EntityManager em = CaseLotBuy.entityManager();
        TypedQuery<CaseLotBuy> q = em.createQuery("SELECT o FROM CaseLotBuy AS o WHERE o.caselotId = :caselotId", CaseLotBuy.class);
        q.setParameter("caselotId", caselotId);
        return q;
    }
    
    public static TypedQuery<CaseLotBuy> CaseLotBuy.findCaseLotBuysByCaselotIdAndBuyType(String caselotId, Integer buyType) {
        if (caselotId == null || caselotId.length() == 0) throw new IllegalArgumentException("The caselotId argument is required");
        if (buyType == null) throw new IllegalArgumentException("The buyType argument is required");
        EntityManager em = CaseLotBuy.entityManager();
        TypedQuery<CaseLotBuy> q = em.createQuery("SELECT o FROM CaseLotBuy AS o WHERE o.caselotId = :caselotId AND o.buyType = :buyType", CaseLotBuy.class);
        q.setParameter("caselotId", caselotId);
        q.setParameter("buyType", buyType);
        return q;
    }
    
    public static TypedQuery<CaseLotBuy> CaseLotBuy.findCaseLotBuysByUserno(String userno) {
        if (userno == null || userno.length() == 0) throw new IllegalArgumentException("The userno argument is required");
        EntityManager em = CaseLotBuy.entityManager();
        TypedQuery<CaseLotBuy> q = em.createQuery("SELECT o FROM CaseLotBuy AS o WHERE o.userno = :userno", CaseLotBuy.class);
        q.setParameter("userno", userno);
        return q;
    }
    
}
