// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.Boolean;
import java.lang.String;
import java.util.Date;

privileged aspect CaseLotCelebrity_Roo_JavaBean {
    
    public String CaseLotCelebrity.getUserno() {
        return this.userno;
    }
    
    public void CaseLotCelebrity.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String CaseLotCelebrity.getLotno() {
        return this.lotno;
    }
    
    public void CaseLotCelebrity.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public int CaseLotCelebrity.getSortno() {
        return this.sortno;
    }
    
    public void CaseLotCelebrity.setSortno(int sortno) {
        this.sortno = sortno;
    }
    
    public Date CaseLotCelebrity.getLastModifyTime() {
        return this.lastModifyTime;
    }
    
    public void CaseLotCelebrity.setLastModifyTime(Date lastModifyTime) {
        this.lastModifyTime = lastModifyTime;
    }
    
    public Boolean CaseLotCelebrity.getEnable() {
        return this.enable;
    }
    
    public void CaseLotCelebrity.setEnable(Boolean enable) {
        this.enable = enable;
    }
    
}
