// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.CaseLot;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CaseLot_Roo_Entity {
    
    declare @type: CaseLot: @Entity;
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager CaseLot.entityManager;
    
    @Transactional
    public void CaseLot.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void CaseLot.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            CaseLot attached = CaseLot.findCaseLot(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void CaseLot.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void CaseLot.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public CaseLot CaseLot.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        CaseLot merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager CaseLot.entityManager() {
        EntityManager em = new CaseLot().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long CaseLot.countCaseLots() {
        return entityManager().createQuery("SELECT COUNT(o) FROM CaseLot o", Long.class).getSingleResult();
    }
    
    public static List<CaseLot> CaseLot.findAllCaseLots() {
        return entityManager().createQuery("SELECT o FROM CaseLot o", CaseLot.class).getResultList();
    }
    
    public static List<CaseLot> CaseLot.findCaseLotEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM CaseLot o", CaseLot.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
