// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.CompositePK;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect CompositePK_Roo_Json {
    
    public String CompositePK.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static CompositePK CompositePK.fromJsonToCompositePK(String json) {
        return new JSONDeserializer<CompositePK>().use(null, CompositePK.class).deserialize(json);
    }
    
    public static String CompositePK.toJsonArray(Collection<CompositePK> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<CompositePK> CompositePK.fromJsonArrayToCompositePKs(String json) {
        return new JSONDeserializer<List<CompositePK>>().use(null, ArrayList.class).use("values", CompositePK.class).deserialize(json);
    }
    
}
