// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.Object;
import java.lang.String;
import javax.persistence.Embeddable;

privileged aspect CompositePK_Roo_Identifier {
    
    declare @type: CompositePK: @Embeddable;
    
    public CompositePK.new(String lotno, String batchcode, String agencyno) {
        super();
        this.lotno = lotno;
        this.batchcode = batchcode;
        this.agencyno = agencyno;
    }

    private CompositePK.new() {
        super();
    }

    public String CompositePK.getLotno() {
        return this.lotno;
    }
    
    public String CompositePK.getBatchcode() {
        return this.batchcode;
    }
    
    public String CompositePK.getAgencyno() {
        return this.agencyno;
    }
    
    public boolean CompositePK.equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (!(obj instanceof CompositePK)) return false;
        CompositePK other = (CompositePK) obj;
        if (lotno == null) {
            if (other.lotno != null) return false;
        } else if (!lotno.equals(other.lotno)) return false;
        if (batchcode == null) {
            if (other.batchcode != null) return false;
        } else if (!batchcode.equals(other.batchcode)) return false;
        if (agencyno == null) {
            if (other.agencyno != null) return false;
        } else if (!agencyno.equals(other.agencyno)) return false;
        return true;
    }
    
    public int CompositePK.hashCode() {
        final int prime = 31;
        int result = 17;
        result = prime * result + (lotno == null ? 0 : lotno.hashCode());
        result = prime * result + (batchcode == null ? 0 : batchcode.hashCode());
        result = prime * result + (agencyno == null ? 0 : agencyno.hashCode());
        return result;
    }
    
}
