// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect CreateUserEventLog_Roo_JavaBean {
    
    public String CreateUserEventLog.getId() {
        return this.id;
    }
    
    public void CreateUserEventLog.setId(String id) {
        this.id = id;
    }
    
    public String CreateUserEventLog.getUsername() {
        return this.username;
    }
    
    public void CreateUserEventLog.setUsername(String username) {
        this.username = username;
    }
    
    public String CreateUserEventLog.getMemo() {
        return this.memo;
    }
    
    public void CreateUserEventLog.setMemo(String memo) {
        this.memo = memo;
    }
    
    public String CreateUserEventLog.getCreatetime() {
        return this.createtime;
    }
    
    public void CreateUserEventLog.setCreatetime(String createtime) {
        this.createtime = createtime;
    }
    
}
