// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.CreateUserEventLog;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CreateUserEventLog_Roo_Entity {
    
    declare @type: CreateUserEventLog: @Entity;
    
    declare @type: CreateUserEventLog: @Table(name = "CREATEUSEREVENTLOG", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager CreateUserEventLog.entityManager;
    
    @Transactional
    public void CreateUserEventLog.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void CreateUserEventLog.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            CreateUserEventLog attached = CreateUserEventLog.findCreateUserEventLog(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void CreateUserEventLog.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void CreateUserEventLog.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public CreateUserEventLog CreateUserEventLog.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        CreateUserEventLog merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager CreateUserEventLog.entityManager() {
        EntityManager em = new CreateUserEventLog().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long CreateUserEventLog.countCreateUserEventLogs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM CreateUserEventLog o", Long.class).getSingleResult();
    }
    
    public static List<CreateUserEventLog> CreateUserEventLog.findAllCreateUserEventLogs() {
        return entityManager().createQuery("SELECT o FROM CreateUserEventLog o", CreateUserEventLog.class).getResultList();
    }
    
    public static CreateUserEventLog CreateUserEventLog.findCreateUserEventLog(String id) {
        if (id == null || id.length() == 0) return null;
        return entityManager().find(CreateUserEventLog.class, id);
    }
    
    public static List<CreateUserEventLog> CreateUserEventLog.findCreateUserEventLogEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM CreateUserEventLog o", CreateUserEventLog.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
