// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.MsgMonitorCompositePK;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect MsgMonitorCompositePK_Roo_Json {
    
    public String MsgMonitorCompositePK.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static MsgMonitorCompositePK MsgMonitorCompositePK.fromJsonToMsgMonitorCompositePK(String json) {
        return new JSONDeserializer<MsgMonitorCompositePK>().use(null, MsgMonitorCompositePK.class).deserialize(json);
    }
    
    public static String MsgMonitorCompositePK.toJsonArray(Collection<MsgMonitorCompositePK> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<MsgMonitorCompositePK> MsgMonitorCompositePK.fromJsonArrayToMsgMonitorCompositePKs(String json) {
        return new JSONDeserializer<List<MsgMonitorCompositePK>>().use(null, ArrayList.class).use("values", MsgMonitorCompositePK.class).deserialize(json);
    }
    
}
