// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.Integer;
import java.lang.String;

privileged aspect Tactivities_Roo_JavaBean {
    
    public String Tactivities.getLotno() {
        return this.lotno;
    }
    
    public void Tactivities.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public String Tactivities.getSubChannel() {
        return this.subChannel;
    }
    
    public void Tactivities.setSubChannel(String subChannel) {
        this.subChannel = subChannel;
    }
    
    public String Tactivities.getChannel() {
        return this.channel;
    }
    
    public void Tactivities.setChannel(String channel) {
        this.channel = channel;
    }
    
    public Integer Tactivities.getActivityType() {
        return this.activityType;
    }
    
    public void Tactivities.setActivityType(Integer activityType) {
        this.activityType = activityType;
    }
    
    public String Tactivities.getAmt() {
        return this.amt;
    }
    
    public void Tactivities.setAmt(String amt) {
        this.amt = amt;
    }
    
    public Integer Tactivities.getState() {
        return this.state;
    }
    
    public void Tactivities.setState(Integer state) {
        this.state = state;
    }
    
}
