// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tawardlevel;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Tawardlevel_Roo_Json {
    
    public String Tawardlevel.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Tawardlevel Tawardlevel.fromJsonToTawardlevel(String json) {
        return new JSONDeserializer<Tawardlevel>().use(null, Tawardlevel.class).deserialize(json);
    }
    
    public static String Tawardlevel.toJsonArray(Collection<Tawardlevel> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Tawardlevel> Tawardlevel.fromJsonArrayToTawardlevels(String json) {
        return new JSONDeserializer<List<Tawardlevel>>().use(null, ArrayList.class).use("values", Tawardlevel.class).deserialize(json);
    }
    
}
