// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;

privileged aspect Tawardlevel_Roo_JavaBean {
    
    public BigDecimal Tawardlevel.getId() {
        return this.id;
    }
    
    public void Tawardlevel.setId(BigDecimal id) {
        this.id = id;
    }
    
    public String Tawardlevel.getLotno() {
        return this.lotno;
    }
    
    public void Tawardlevel.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public String Tawardlevel.getLevel() {
        return this.level;
    }
    
    public void Tawardlevel.setLevel(String level) {
        this.level = level;
    }
    
    public String Tawardlevel.getName() {
        return this.name;
    }
    
    public void Tawardlevel.setName(String name) {
        this.name = name;
    }
    
    public long Tawardlevel.getLevelprize() {
        return this.levelprize;
    }
    
    public void Tawardlevel.setLevelprize(long levelprize) {
        this.levelprize = levelprize;
    }
    
    public long Tawardlevel.getAddprize() {
        return this.addprize;
    }
    
    public void Tawardlevel.setAddprize(long addprize) {
        this.addprize = addprize;
    }
    
}
