// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.TawardDetail;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect TawardDetail_Roo_Json {
    
    public String TawardDetail.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static TawardDetail TawardDetail.fromJsonToTawardDetail(String json) {
        return new JSONDeserializer<TawardDetail>().use(null, TawardDetail.class).deserialize(json);
    }
    
    public static String TawardDetail.toJsonArray(Collection<TawardDetail> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<TawardDetail> TawardDetail.fromJsonArrayToTawardDetails(String json) {
        return new JSONDeserializer<List<TawardDetail>>().use(null, ArrayList.class).use("values", TawardDetail.class).deserialize(json);
    }
    
}
