// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.TawardDetail;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TawardDetail_Roo_Entity {
    
    declare @type: TawardDetail: @Entity;
    
    declare @type: TawardDetail: @Table(name = "TAWARDDETAIL", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager TawardDetail.entityManager;
    
    @Transactional
    public void TawardDetail.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void TawardDetail.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            TawardDetail attached = TawardDetail.findTawardDetail(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void TawardDetail.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void TawardDetail.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public TawardDetail TawardDetail.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        TawardDetail merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager TawardDetail.entityManager() {
        EntityManager em = new TawardDetail().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long TawardDetail.countTawardDetails() {
        return entityManager().createQuery("SELECT COUNT(o) FROM TawardDetail o", Long.class).getSingleResult();
    }
    
    public static List<TawardDetail> TawardDetail.findAllTawardDetails() {
        return entityManager().createQuery("SELECT o FROM TawardDetail o", TawardDetail.class).getResultList();
    }
    
    public static TawardDetail TawardDetail.findTawardDetail(BigDecimal id) {
        if (id == null) return null;
        return entityManager().find(TawardDetail.class, id);
    }
    
    public static List<TawardDetail> TawardDetail.findTawardDetailEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM TawardDetail o", TawardDetail.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
