// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tbelonginfo_Roo_ToString {
    
    public String Tbelonginfo.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("BprovCode: ").append(getBprovCode()).append(", ");
        sb.append("BprovName: ").append(getBprovName()).append(", ");
        sb.append("ProvCode: ").append(getProvCode()).append(", ");
        sb.append("ProvName: ").append(getProvName());
        return sb.toString();
    }
    
}
