// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tbiguserinfo;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tbiguserinfo_Roo_Entity {
    
    declare @type: Tbiguserinfo: @Entity;
    
    declare @type: Tbiguserinfo: @Table(name = "TBIGUSERINFO", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tbiguserinfo.entityManager;
    
    @Transactional
    public void Tbiguserinfo.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tbiguserinfo.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tbiguserinfo attached = Tbiguserinfo.findTbiguserinfo(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tbiguserinfo.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tbiguserinfo.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tbiguserinfo Tbiguserinfo.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tbiguserinfo merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tbiguserinfo.entityManager() {
        EntityManager em = new Tbiguserinfo().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tbiguserinfo.countTbiguserinfoes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tbiguserinfo o", Long.class).getSingleResult();
    }
    
    public static List<Tbiguserinfo> Tbiguserinfo.findAllTbiguserinfoes() {
        return entityManager().createQuery("SELECT o FROM Tbiguserinfo o", Tbiguserinfo.class).getResultList();
    }
    
    public static Tbiguserinfo Tbiguserinfo.findTbiguserinfo(BigDecimal id) {
        if (id == null) return null;
        return entityManager().find(Tbiguserinfo.class, id);
    }
    
    public static List<Tbiguserinfo> Tbiguserinfo.findTbiguserinfoEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tbiguserinfo o", Tbiguserinfo.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
