// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tcashrecordcfg_Roo_ToString {
    
    public String Tcashrecordcfg.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Amt: ").append(getAmt()).append(", ");
        sb.append("Cashrecordid: ").append(getCashrecordid()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("Num: ").append(getNum()).append(", ");
        sb.append("Ttransactionid: ").append(getTtransactionid());
        return sb.toString();
    }
    
}
