// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.math.BigDecimal;
import java.util.Date;

privileged aspect Tcashrecord_Roo_JavaBean {
    
    public BigDecimal Tcashrecord.getId() {
        return this.id;
    }
    
    public void Tcashrecord.setId(BigDecimal id) {
        this.id = id;
    }
    
    public Date Tcashrecord.getDcdate() {
        return this.dcdate;
    }
    
    public void Tcashrecord.setDcdate(Date dcdate) {
        this.dcdate = dcdate;
    }
    
    public BigDecimal Tcashrecord.getAmt() {
        return this.amt;
    }
    
    public void Tcashrecord.setAmt(BigDecimal amt) {
        this.amt = amt;
    }
    
}
