// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tcashrecord;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tcashrecord_Roo_Entity {
    
    declare @type: Tcashrecord: @Entity;
    
    declare @type: Tcashrecord: @Table(name = "TCASHRECORD", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tcashrecord.entityManager;
    
    @Transactional
    public void Tcashrecord.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tcashrecord.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tcashrecord attached = Tcashrecord.findTcashrecord(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tcashrecord.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tcashrecord.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tcashrecord Tcashrecord.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tcashrecord merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tcashrecord.entityManager() {
        EntityManager em = new Tcashrecord().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tcashrecord.countTcashrecords() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tcashrecord o", Long.class).getSingleResult();
    }
    
    public static List<Tcashrecord> Tcashrecord.findAllTcashrecords() {
        return entityManager().createQuery("SELECT o FROM Tcashrecord o", Tcashrecord.class).getResultList();
    }
    
    public static Tcashrecord Tcashrecord.findTcashrecord(BigDecimal id) {
        if (id == null) return null;
        return entityManager().find(Tcashrecord.class, id);
    }
    
    public static List<Tcashrecord> Tcashrecord.findTcashrecordEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tcashrecord o", Tcashrecord.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
