// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tcashrecord_Roo_ToString {
    
    public String Tcashrecord.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Amt: ").append(getAmt()).append(", ");
        sb.append("Dcdate: ").append(getDcdate()).append(", ");
        sb.append("Id: ").append(getId());
        return sb.toString();
    }
    
}
