// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;

privileged aspect Tcashrecordcfg_Roo_JavaBean {
    
    public BigDecimal Tcashrecordcfg.getId() {
        return this.id;
    }
    
    public void Tcashrecordcfg.setId(BigDecimal id) {
        this.id = id;
    }
    
    public BigDecimal Tcashrecordcfg.getCashrecordid() {
        return this.cashrecordid;
    }
    
    public void Tcashrecordcfg.setCashrecordid(BigDecimal cashrecordid) {
        this.cashrecordid = cashrecordid;
    }
    
    public String Tcashrecordcfg.getTtransactionid() {
        return this.ttransactionid;
    }
    
    public void Tcashrecordcfg.setTtransactionid(String ttransactionid) {
        this.ttransactionid = ttransactionid;
    }
    
    public int Tcashrecordcfg.getNum() {
        return this.num;
    }
    
    public void Tcashrecordcfg.setNum(int num) {
        this.num = num;
    }
    
    public BigDecimal Tcashrecordcfg.getAmt() {
        return this.amt;
    }
    
    public void Tcashrecordcfg.setAmt(BigDecimal amt) {
        this.amt = amt;
    }
    
    public String Tcashrecordcfg.getName() {
        return this.name;
    }
    
    public void Tcashrecordcfg.setName(String name) {
        this.name = name;
    }
    
}
