// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tcwtj;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Tcwtj_Roo_Json {
    
    public String Tcwtj.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Tcwtj Tcwtj.fromJsonToTcwtj(String json) {
        return new JSONDeserializer<Tcwtj>().use(null, Tcwtj.class).deserialize(json);
    }
    
    public static String Tcwtj.toJsonArray(Collection<Tcwtj> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Tcwtj> Tcwtj.fromJsonArrayToTcwtjs(String json) {
        return new JSONDeserializer<List<Tcwtj>>().use(null, ArrayList.class).use("values", Tcwtj.class).deserialize(json);
    }
    
}
