// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tcwtj_Roo_ToString {
    
    public String Tcwtj.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Activitypersent: ").append(getActivitypersent()).append(", ");
        sb.append("Balance: ").append(getBalance()).append(", ");
        sb.append("Cannel: ").append(getCannel()).append(", ");
        sb.append("Channelbet: ").append(getChannelbet()).append(", ");
        sb.append("Channelcharge: ").append(getChannelcharge()).append(", ");
        sb.append("Chargepersent: ").append(getChargepersent()).append(", ");
        sb.append("Draw: ").append(getDraw()).append(", ");
        sb.append("Encash: ").append(getEncash()).append(", ");
        sb.append("Fee: ").append(getFee()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Inhj: ").append(getInhj()).append(", ");
        sb.append("Memo: ").append(getMemo()).append(", ");
        sb.append("Other1: ").append(getOther1()).append(", ");
        sb.append("Outhj: ").append(getOuthj()).append(", ");
        sb.append("Tjdate: ").append(getTjdate()).append(", ");
        sb.append("Userbet: ").append(getUserbet()).append(", ");
        sb.append("Usercharge: ").append(getUsercharge());
        return sb.toString();
    }
    
}
