// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tdnabind_Roo_ToString {
    
    public String Tdnabind.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Bankaddress: ").append(getBankaddress()).append(", ");
        sb.append("Bankcardno: ").append(getBankcardno()).append(", ");
        sb.append("Bankname: ").append(getBankname()).append(", ");
        sb.append("Bindtime: ").append(getBindtime()).append(", ");
        sb.append("Certid: ").append(getCertid()).append(", ");
        sb.append("Certidaddress: ").append(getCertidaddress()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Mobileid: ").append(getMobileid()).append(", ");
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("Userno: ").append(getUserno());
        return sb.toString();
    }
    
}
