// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tfeeformula_Roo_ToString {
    
    public String Tfeeformula.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Feerate: ").append(getFeerate()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Lowerlimit: ").append(getLowerlimit()).append(", ");
        sb.append("Memo: ").append(getMemo()).append(", ");
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("Regtime: ").append(getRegtime()).append(", ");
        sb.append("Tloguserid: ").append(getTloguserid()).append(", ");
        sb.append("Ttransactionid: ").append(getTtransactionid()).append(", ");
        sb.append("Upperlimit: ").append(getUpperlimit());
        return sb.toString();
    }
    
}
