// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Tfeeformula_Roo_JavaBean {
    
    public String Tfeeformula.getId() {
        return this.id;
    }
    
    public void Tfeeformula.setId(String id) {
        this.id = id;
    }
    
    public String Tfeeformula.getTtransactionid() {
        return this.ttransactionid;
    }
    
    public void Tfeeformula.setTtransactionid(String ttransactionid) {
        this.ttransactionid = ttransactionid;
    }
    
    public String Tfeeformula.getName() {
        return this.name;
    }
    
    public void Tfeeformula.setName(String name) {
        this.name = name;
    }
    
    public String Tfeeformula.getMemo() {
        return this.memo;
    }
    
    public void Tfeeformula.setMemo(String memo) {
        this.memo = memo;
    }
    
    public BigDecimal Tfeeformula.getFeerate() {
        return this.feerate;
    }
    
    public void Tfeeformula.setFeerate(BigDecimal feerate) {
        this.feerate = feerate;
    }
    
    public BigDecimal Tfeeformula.getLowerlimit() {
        return this.lowerlimit;
    }
    
    public void Tfeeformula.setLowerlimit(BigDecimal lowerlimit) {
        this.lowerlimit = lowerlimit;
    }
    
    public BigDecimal Tfeeformula.getUpperlimit() {
        return this.upperlimit;
    }
    
    public void Tfeeformula.setUpperlimit(BigDecimal upperlimit) {
        this.upperlimit = upperlimit;
    }
    
    public Date Tfeeformula.getRegtime() {
        return this.regtime;
    }
    
    public void Tfeeformula.setRegtime(Date regtime) {
        this.regtime = regtime;
    }
    
    public String Tfeeformula.getTloguserid() {
        return this.tloguserid;
    }
    
    public void Tfeeformula.setTloguserid(String tloguserid) {
        this.tloguserid = tloguserid;
    }
    
}
