// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tgift;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tgift_Roo_Entity {
    
    declare @type: Tgift: @Entity;
    
    declare @type: Tgift: @Table(name = "TGIFT", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tgift.entityManager;
    
    @Transactional
    public void Tgift.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tgift.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tgift attached = Tgift.findTgift(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tgift.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tgift.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tgift Tgift.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tgift merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tgift.entityManager() {
        EntityManager em = new Tgift().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tgift.countTgifts() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tgift o", Long.class).getSingleResult();
    }
    
    public static List<Tgift> Tgift.findAllTgifts() {
        return entityManager().createQuery("SELECT o FROM Tgift o", Tgift.class).getResultList();
    }
    
    public static Tgift Tgift.findTgift(String id) {
        if (id == null || id.length() == 0) return null;
        return entityManager().find(Tgift.class, id);
    }
    
    public static List<Tgift> Tgift.findTgiftEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tgift o", Tgift.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
