// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tgiftaudit;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Tgiftaudit_Roo_Json {
    
    public String Tgiftaudit.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Tgiftaudit Tgiftaudit.fromJsonToTgiftaudit(String json) {
        return new JSONDeserializer<Tgiftaudit>().use(null, Tgiftaudit.class).deserialize(json);
    }
    
    public static String Tgiftaudit.toJsonArray(Collection<Tgiftaudit> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Tgiftaudit> Tgiftaudit.fromJsonArrayToTgiftaudits(String json) {
        return new JSONDeserializer<List<Tgiftaudit>>().use(null, ArrayList.class).use("values", Tgiftaudit.class).deserialize(json);
    }
    
}
