// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.Integer;
import java.lang.Long;
import java.lang.String;
import java.util.Date;

privileged aspect Tgiftaudit_Roo_JavaBean {
    
    public String Tgiftaudit.getId() {
        return this.id;
    }
    
    public void Tgiftaudit.setId(String id) {
        this.id = id;
    }
    
    public String Tgiftaudit.getBiguserno() {
        return this.biguserno;
    }
    
    public void Tgiftaudit.setBiguserno(String biguserno) {
        this.biguserno = biguserno;
    }
    
    public String Tgiftaudit.getBigname() {
        return this.bigname;
    }
    
    public void Tgiftaudit.setBigname(String bigname) {
        this.bigname = bigname;
    }
    
    public Long Tgiftaudit.getAllamt() {
        return this.allamt;
    }
    
    public void Tgiftaudit.setAllamt(Long allamt) {
        this.allamt = allamt;
    }
    
    public String Tgiftaudit.getFlowno() {
        return this.flowno;
    }
    
    public void Tgiftaudit.setFlowno(String flowno) {
        this.flowno = flowno;
    }
    
    public Integer Tgiftaudit.getFlag() {
        return this.flag;
    }
    
    public void Tgiftaudit.setFlag(Integer flag) {
        this.flag = flag;
    }
    
    public String Tgiftaudit.getLotno() {
        return this.lotno;
    }
    
    public void Tgiftaudit.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public Long Tgiftaudit.getBetnum() {
        return this.betnum;
    }
    
    public void Tgiftaudit.setBetnum(Long betnum) {
        this.betnum = betnum;
    }
    
    public Long Tgiftaudit.getSuccess() {
        return this.success;
    }
    
    public void Tgiftaudit.setSuccess(Long success) {
        this.success = success;
    }
    
    public Long Tgiftaudit.getFailure() {
        return this.failure;
    }
    
    public void Tgiftaudit.setFailure(Long failure) {
        this.failure = failure;
    }
    
    public Date Tgiftaudit.getAgetime() {
        return this.agetime;
    }
    
    public void Tgiftaudit.setAgetime(Date agetime) {
        this.agetime = agetime;
    }
    
    public Date Tgiftaudit.getAftertime() {
        return this.aftertime;
    }
    
    public void Tgiftaudit.setAftertime(Date aftertime) {
        this.aftertime = aftertime;
    }
    
    public String Tgiftaudit.getSmscontent() {
        return this.smscontent;
    }
    
    public void Tgiftaudit.setSmscontent(String smscontent) {
        this.smscontent = smscontent;
    }
    
    public String Tgiftaudit.getAgencycode() {
        return this.agencycode;
    }
    
    public void Tgiftaudit.setAgencycode(String agencycode) {
        this.agencycode = agencycode;
    }
    
}
