// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tlogic_Roo_ToString {
    
    public String Tlogic.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Moneycount: ").append(getMoneycount()).append(", ");
        sb.append("Num: ").append(getNum()).append(", ");
        sb.append("Selldate: ").append(getSelldate());
        return sb.toString();
    }
    
}
