// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tloguser;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tloguser_Roo_Entity {
    
    declare @type: Tloguser: @Entity;
    
    declare @type: Tloguser: @Table(name = "TLOGUSER", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tloguser.entityManager;
    
    @Transactional
    public void Tloguser.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tloguser.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tloguser attached = Tloguser.findTloguser(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tloguser.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tloguser.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tloguser Tloguser.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tloguser merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tloguser.entityManager() {
        EntityManager em = new Tloguser().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tloguser.countTlogusers() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tloguser o", Long.class).getSingleResult();
    }
    
    public static List<Tloguser> Tloguser.findAllTlogusers() {
        return entityManager().createQuery("SELECT o FROM Tloguser o", Tloguser.class).getResultList();
    }
    
    public static Tloguser Tloguser.findTloguser(String id) {
        if (id == null || id.length() == 0) return null;
        return entityManager().find(Tloguser.class, id);
    }
    
    public static List<Tloguser> Tloguser.findTloguserEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tloguser o", Tloguser.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
