// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tlogic;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tlogic_Roo_Entity {
    
    declare @type: Tlogic: @Entity;
    
    declare @type: Tlogic: @Table(name = "TLOGIC", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tlogic.entityManager;
    
    @Transactional
    public void Tlogic.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tlogic.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tlogic attached = Tlogic.findTlogic(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tlogic.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tlogic.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tlogic Tlogic.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tlogic merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tlogic.entityManager() {
        EntityManager em = new Tlogic().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tlogic.countTlogics() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tlogic o", Long.class).getSingleResult();
    }
    
    public static List<Tlogic> Tlogic.findAllTlogics() {
        return entityManager().createQuery("SELECT o FROM Tlogic o", Tlogic.class).getResultList();
    }
    
    public static Tlogic Tlogic.findTlogic(BigDecimal id) {
        if (id == null) return null;
        return entityManager().find(Tlogic.class, id);
    }
    
    public static List<Tlogic> Tlogic.findTlogicEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tlogic o", Tlogic.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
