// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;

privileged aspect Tlogic_Roo_JavaBean {
    
    public BigDecimal Tlogic.getId() {
        return this.id;
    }
    
    public void Tlogic.setId(BigDecimal id) {
        this.id = id;
    }
    
    public BigDecimal Tlogic.getNum() {
        return this.num;
    }
    
    public void Tlogic.setNum(BigDecimal num) {
        this.num = num;
    }
    
    public BigDecimal Tlogic.getMoneycount() {
        return this.moneycount;
    }
    
    public void Tlogic.setMoneycount(BigDecimal moneycount) {
        this.moneycount = moneycount;
    }
    
    public String Tlogic.getSelldate() {
        return this.selldate;
    }
    
    public void Tlogic.setSelldate(String selldate) {
        this.selldate = selldate;
    }
    
}
