// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect TlotmapPK_Roo_ToString {
    
    public String TlotmapPK.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Agencyflowno: ").append(getAgencyflowno()).append(", ");
        sb.append("Agencyno: ").append(getAgencyno());
        return sb.toString();
    }
    
}
