// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.CompositePK;
import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect TlotcenterDuizhang_Roo_JavaBean {
    
    public CompositePK TlotcenterDuizhang.getId() {
        return this.id;
    }
    
    public void TlotcenterDuizhang.setId(CompositePK id) {
        this.id = id;
    }
    
    public BigDecimal TlotcenterDuizhang.getLotcenteramt() {
        return this.lotcenteramt;
    }
    
    public void TlotcenterDuizhang.setLotcenteramt(BigDecimal lotcenteramt) {
        this.lotcenteramt = lotcenteramt;
    }
    
    public BigDecimal TlotcenterDuizhang.getAmt() {
        return this.amt;
    }
    
    public void TlotcenterDuizhang.setAmt(BigDecimal amt) {
        this.amt = amt;
    }
    
    public BigDecimal TlotcenterDuizhang.getLotcenterprizeamt() {
        return this.lotcenterprizeamt;
    }
    
    public void TlotcenterDuizhang.setLotcenterprizeamt(BigDecimal lotcenterprizeamt) {
        this.lotcenterprizeamt = lotcenterprizeamt;
    }
    
    public BigDecimal TlotcenterDuizhang.getPrizeamt() {
        return this.prizeamt;
    }
    
    public void TlotcenterDuizhang.setPrizeamt(BigDecimal prizeamt) {
        this.prizeamt = prizeamt;
    }
    
    public String TlotcenterDuizhang.getMemo() {
        return this.memo;
    }
    
    public void TlotcenterDuizhang.setMemo(String memo) {
        this.memo = memo;
    }
    
    public BigDecimal TlotcenterDuizhang.getSellstate() {
        return this.sellstate;
    }
    
    public void TlotcenterDuizhang.setSellstate(BigDecimal sellstate) {
        this.sellstate = sellstate;
    }
    
    public BigDecimal TlotcenterDuizhang.getEncashstate() {
        return this.encashstate;
    }
    
    public void TlotcenterDuizhang.setEncashstate(BigDecimal encashstate) {
        this.encashstate = encashstate;
    }
    
    public Date TlotcenterDuizhang.getCreatetime() {
        return this.createtime;
    }
    
    public void TlotcenterDuizhang.setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
}
