// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.CompositePK;
import com.ruyicai.mgr.domain.TlotcenterDuizhang;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TlotcenterDuizhang_Roo_Entity {
    
    declare @type: TlotcenterDuizhang: @Entity;
    
    declare @type: TlotcenterDuizhang: @Table(name = "TLOTCENTERDUIZHANG", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager TlotcenterDuizhang.entityManager;
    
    @Transactional
    public void TlotcenterDuizhang.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void TlotcenterDuizhang.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            TlotcenterDuizhang attached = TlotcenterDuizhang.findTlotcenterDuizhang(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void TlotcenterDuizhang.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void TlotcenterDuizhang.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public TlotcenterDuizhang TlotcenterDuizhang.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        TlotcenterDuizhang merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager TlotcenterDuizhang.entityManager() {
        EntityManager em = new TlotcenterDuizhang().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long TlotcenterDuizhang.countTlotcenterDuizhangs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM TlotcenterDuizhang o", Long.class).getSingleResult();
    }
    
    public static List<TlotcenterDuizhang> TlotcenterDuizhang.findAllTlotcenterDuizhangs() {
        return entityManager().createQuery("SELECT o FROM TlotcenterDuizhang o", TlotcenterDuizhang.class).getResultList();
    }
    
    public static TlotcenterDuizhang TlotcenterDuizhang.findTlotcenterDuizhang(CompositePK id) {
        if (id == null) return null;
        return entityManager().find(TlotcenterDuizhang.class, id);
    }
    
    public static List<TlotcenterDuizhang> TlotcenterDuizhang.findTlotcenterDuizhangEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM TlotcenterDuizhang o", TlotcenterDuizhang.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
