// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.TlotmapPK;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect TlotmapPK_Roo_Json {
    
    public String TlotmapPK.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static TlotmapPK TlotmapPK.fromJsonToTlotmapPK(String json) {
        return new JSONDeserializer<TlotmapPK>().use(null, TlotmapPK.class).deserialize(json);
    }
    
    public static String TlotmapPK.toJsonArray(Collection<TlotmapPK> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<TlotmapPK> TlotmapPK.fromJsonArrayToTlotmapPKs(String json) {
        return new JSONDeserializer<List<TlotmapPK>>().use(null, ArrayList.class).use("values", TlotmapPK.class).deserialize(json);
    }
    
}
