// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tlotctrl_Roo_ToString {
    
    public String Tlotctrl.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Createtime: ").append(getCreatetime()).append(", ");
        sb.append("Encashstate: ").append(getEncashstate()).append(", ");
        sb.append("Endbettime: ").append(getEndbettime()).append(", ");
        sb.append("Endtime: ").append(getEndtime()).append(", ");
        sb.append("Hemaiendtime: ").append(getHemaiendtime()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Starttime: ").append(getStarttime()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("Tlotctrls: ").append(getTlotctrls() == null ? "null" : getTlotctrls().size());
        return sb.toString();
    }
    
}
