// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tlottypeconfig;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tlottypeconfig_Roo_Entity {
    
    declare @type: Tlottypeconfig: @Entity;
    
    declare @type: Tlottypeconfig: @Table(name = "TLOTTYPECONFIG", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tlottypeconfig.entityManager;
    
    @Transactional
    public void Tlottypeconfig.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tlottypeconfig.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tlottypeconfig attached = Tlottypeconfig.findTlottypeconfig(this.lotno);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tlottypeconfig.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tlottypeconfig.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tlottypeconfig Tlottypeconfig.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tlottypeconfig merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tlottypeconfig.entityManager() {
        EntityManager em = new Tlottypeconfig().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tlottypeconfig.countTlottypeconfigs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tlottypeconfig o", Long.class).getSingleResult();
    }
    
    public static List<Tlottypeconfig> Tlottypeconfig.findAllTlottypeconfigs() {
        return entityManager().createQuery("SELECT o FROM Tlottypeconfig o", Tlottypeconfig.class).getResultList();
    }
    
    public static Tlottypeconfig Tlottypeconfig.findTlottypeconfig(String lotno) {
        if (lotno == null || lotno.length() == 0) return null;
        return entityManager().find(Tlottypeconfig.class, lotno);
    }
    
    public static List<Tlottypeconfig> Tlottypeconfig.findTlottypeconfigEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tlottypeconfig o", Tlottypeconfig.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
