// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tlotresult;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tlotresult_Roo_Entity {
    
    declare @type: Tlotresult: @Entity;
    
    declare @type: Tlotresult: @Table(name = "TLOTRESULT", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tlotresult.entityManager;
    
    @Transactional
    public void Tlotresult.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tlotresult.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tlotresult attached = Tlotresult.findTlotresult(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tlotresult.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tlotresult.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tlotresult Tlotresult.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tlotresult merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tlotresult.entityManager() {
        EntityManager em = new Tlotresult().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tlotresult.countTlotresults() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tlotresult o", Long.class).getSingleResult();
    }
    
    public static List<Tlotresult> Tlotresult.findAllTlotresults() {
        return entityManager().createQuery("SELECT o FROM Tlotresult o", Tlotresult.class).getResultList();
    }
    
    public static Tlotresult Tlotresult.findTlotresult(String id) {
        if (id == null || id.length() == 0) return null;
        return entityManager().find(Tlotresult.class, id);
    }
    
    public static List<Tlotresult> Tlotresult.findTlotresultEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tlotresult o", Tlotresult.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
