// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tlotmap;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Tlotmap_Roo_Json {
    
    public String Tlotmap.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Tlotmap Tlotmap.fromJsonToTlotmap(String json) {
        return new JSONDeserializer<Tlotmap>().use(null, Tlotmap.class).deserialize(json);
    }
    
    public static String Tlotmap.toJsonArray(Collection<Tlotmap> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Tlotmap> Tlotmap.fromJsonArrayToTlotmaps(String json) {
        return new JSONDeserializer<List<Tlotmap>>().use(null, ArrayList.class).use("values", Tlotmap.class).deserialize(json);
    }
    
}
