// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tlotencashstrategy_Roo_JavaBean {
    
    public long Tlotencashstrategy.getId() {
        return this.id;
    }
    
    public void Tlotencashstrategy.setId(long id) {
        this.id = id;
    }
    
    public String Tlotencashstrategy.getUserno() {
        return this.userno;
    }
    
    public void Tlotencashstrategy.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String Tlotencashstrategy.getChannel() {
        return this.channel;
    }
    
    public void Tlotencashstrategy.setChannel(String channel) {
        this.channel = channel;
    }
    
    public String Tlotencashstrategy.getLotno() {
        return this.lotno;
    }
    
    public void Tlotencashstrategy.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public int Tlotencashstrategy.getState() {
        return this.state;
    }
    
    public void Tlotencashstrategy.setState(int state) {
        this.state = state;
    }
    
    public int Tlotencashstrategy.getAmt() {
        return this.amt;
    }
    
    public void Tlotencashstrategy.setAmt(int amt) {
        this.amt = amt;
    }
    
}
