// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;

privileged aspect Tlottypeconfig_Roo_JavaBean {
    
    public String Tlottypeconfig.getLotno() {
        return this.lotno;
    }
    
    public void Tlottypeconfig.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public String Tlottypeconfig.getName() {
        return this.name;
    }
    
    public void Tlottypeconfig.setName(String name) {
        this.name = name;
    }
    
    public BigDecimal Tlottypeconfig.getState() {
        return this.state;
    }
    
    public void Tlottypeconfig.setState(BigDecimal state) {
        this.state = state;
    }
    
    public BigDecimal Tlottypeconfig.getLvl() {
        return this.lvl;
    }
    
    public void Tlottypeconfig.setLvl(BigDecimal lvl) {
        this.lvl = lvl;
    }
    
    public int Tlottypeconfig.getOnprize() {
        return this.onprize;
    }
    
    public void Tlottypeconfig.setOnprize(int onprize) {
        this.onprize = onprize;
    }
    
    public BigDecimal Tlottypeconfig.getAutoencash() {
        return this.autoencash;
    }
    
    public void Tlottypeconfig.setAutoencash(BigDecimal autoencash) {
        this.autoencash = autoencash;
    }
    
    public BigDecimal Tlottypeconfig.getLotcenterisvalid() {
        return this.lotcenterisvalid;
    }
    
    public void Tlottypeconfig.setLotcenterisvalid(BigDecimal lotcenterisvalid) {
        this.lotcenterisvalid = lotcenterisvalid;
    }
    
    public String Tlottypeconfig.getBetendtime() {
        return this.betendtime;
    }
    
    public void Tlottypeconfig.setBetendtime(String betendtime) {
        this.betendtime = betendtime;
    }
    
    public String Tlottypeconfig.getHemaibetendtime() {
        return this.hemaibetendtime;
    }
    
    public void Tlottypeconfig.setHemaibetendtime(String hemaibetendtime) {
        this.hemaibetendtime = hemaibetendtime;
    }
    
}
