// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;

privileged aspect Tlotstrategy_Roo_JavaBean {
    
    public long Tlotstrategy.getId() {
        return this.id;
    }
    
    public void Tlotstrategy.setId(long id) {
        this.id = id;
    }
    
    public String Tlotstrategy.getUserno() {
        return this.userno;
    }
    
    public void Tlotstrategy.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String Tlotstrategy.getChannel() {
        return this.channel;
    }
    
    public void Tlotstrategy.setChannel(String channel) {
        this.channel = channel;
    }
    
    public String Tlotstrategy.getLotno() {
        return this.lotno;
    }
    
    public void Tlotstrategy.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public String Tlotstrategy.getAgencyno() {
        return this.agencyno;
    }
    
    public void Tlotstrategy.setAgencyno(String agencyno) {
        this.agencyno = agencyno;
    }
    
    public String Tlotstrategy.getPlaytype() {
        return this.playtype;
    }
    
    public void Tlotstrategy.setPlaytype(String playtype) {
        this.playtype = playtype;
    }
    
    public int Tlotstrategy.getState() {
        return this.state;
    }
    
    public void Tlotstrategy.setState(int state) {
        this.state = state;
    }
    
    public BigDecimal Tlotstrategy.getAmt() {
        return this.amt;
    }
    
    public void Tlotstrategy.setAmt(BigDecimal amt) {
        this.amt = amt;
    }
    
}
