// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.math.BigDecimal;
import java.util.Date;

privileged aspect Tlotctrl_Roo_JavaBean {
    
    public Date Tlotctrl.getStarttime() {
        return this.starttime;
    }
    
    public void Tlotctrl.setStarttime(Date starttime) {
        this.starttime = starttime;
    }
    
    public Date Tlotctrl.getEndtime() {
        return this.endtime;
    }
    
    public void Tlotctrl.setEndtime(Date endtime) {
        this.endtime = endtime;
    }
    
    public BigDecimal Tlotctrl.getState() {
        return this.state;
    }
    
    public void Tlotctrl.setState(BigDecimal state) {
        this.state = state;
    }
    
    public Date Tlotctrl.getCreatetime() {
        return this.createtime;
    }
    
    public void Tlotctrl.setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    public Date Tlotctrl.getEndbettime() {
        return this.endbettime;
    }
    
    public void Tlotctrl.setEndbettime(Date endbettime) {
        this.endbettime = endbettime;
    }
    
    public Date Tlotctrl.getHemaiendtime() {
        return this.hemaiendtime;
    }
    
    public void Tlotctrl.setHemaiendtime(Date hemaiendtime) {
        this.hemaiendtime = hemaiendtime;
    }
    
    public BigDecimal Tlotctrl.getEncashstate() {
        return this.encashstate;
    }
    
    public void Tlotctrl.setEncashstate(BigDecimal encashstate) {
        this.encashstate = encashstate;
    }
    
}
