// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tlottype_Roo_ToString {
    
    public String Tlottype.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Autoencash: ").append(getAutoencash()).append(", ");
        sb.append("Betendlimit: ").append(getBetendlimit()).append(", ");
        sb.append("CityCode: ").append(getCityCode()).append(", ");
        sb.append("Cname: ").append(getCname()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Lvl: ").append(getLvl()).append(", ");
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("Onprize: ").append(getOnprize()).append(", ");
        sb.append("ProvCode: ").append(getProvCode()).append(", ");
        sb.append("State: ").append(getState());
        return sb.toString();
    }
    
}
