// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tlotencashstrategy;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tlotencashstrategy_Roo_Entity {
    
    declare @type: Tlotencashstrategy: @Entity;
    
    declare @type: Tlotencashstrategy: @Table(name = "TLOTENCASHSTRATEGY", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tlotencashstrategy.entityManager;
    
    @Transactional
    public void Tlotencashstrategy.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tlotencashstrategy.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tlotencashstrategy attached = Tlotencashstrategy.findTlotencashstrategy(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tlotencashstrategy.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tlotencashstrategy.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tlotencashstrategy Tlotencashstrategy.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tlotencashstrategy merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tlotencashstrategy.entityManager() {
        EntityManager em = new Tlotencashstrategy().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tlotencashstrategy.countTlotencashstrategys() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tlotencashstrategy o", Long.class).getSingleResult();
    }
    
    public static List<Tlotencashstrategy> Tlotencashstrategy.findAllTlotencashstrategys() {
        return entityManager().createQuery("SELECT o FROM Tlotencashstrategy o", Tlotencashstrategy.class).getResultList();
    }
    
    public static Tlotencashstrategy Tlotencashstrategy.findTlotencashstrategy(long id) {
        return entityManager().find(Tlotencashstrategy.class, id);
    }
    
    public static List<Tlotencashstrategy> Tlotencashstrategy.findTlotencashstrategyEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tlotencashstrategy o", Tlotencashstrategy.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
