// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;

privileged aspect Tmenu_Roo_JavaBean {
    
    public BigDecimal Tmenu.getId() {
        return this.id;
    }
    
    public void Tmenu.setId(BigDecimal id) {
        this.id = id;
    }
    
    public BigDecimal Tmenu.getInid() {
        return this.inid;
    }
    
    public void Tmenu.setInid(BigDecimal inid) {
        this.inid = inid;
    }
    
    public String Tmenu.getName() {
        return this.name;
    }
    
    public void Tmenu.setName(String name) {
        this.name = name;
    }
    
    public String Tmenu.getUrl() {
        return this.url;
    }
    
    public void Tmenu.setUrl(String url) {
        this.url = url;
    }
    
}
