// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tmenu;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tmenu_Roo_Entity {
    
    declare @type: Tmenu: @Entity;
    
    declare @type: Tmenu: @Table(name = "TMENUNEW", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tmenu.entityManager;
    
    @Transactional
    public void Tmenu.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tmenu.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tmenu attached = Tmenu.findTmenu(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tmenu.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tmenu.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tmenu Tmenu.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tmenu merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tmenu.entityManager() {
        EntityManager em = new Tmenu().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tmenu.countTmenus() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tmenu o", Long.class).getSingleResult();
    }
    
    public static List<Tmenu> Tmenu.findAllTmenus() {
        return entityManager().createQuery("SELECT o FROM Tmenu o", Tmenu.class).getResultList();
    }
    
    public static Tmenu Tmenu.findTmenu(BigDecimal id) {
        if (id == null) return null;
        return entityManager().find(Tmenu.class, id);
    }
    
    public static List<Tmenu> Tmenu.findTmenuEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tmenu o", Tmenu.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
