// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tmobileseq_Roo_JavaBean {
    
    public String Tmobileseq.getId() {
        return this.id;
    }
    
    public void Tmobileseq.setId(String id) {
        this.id = id;
    }
    
    public String Tmobileseq.getProvCode() {
        return this.provCode;
    }
    
    public void Tmobileseq.setProvCode(String provCode) {
        this.provCode = provCode;
    }
    
    public String Tmobileseq.getAreaCode() {
        return this.areaCode;
    }
    
    public void Tmobileseq.setAreaCode(String areaCode) {
        this.areaCode = areaCode;
    }
    
    public String Tmobileseq.getSimType() {
        return this.simType;
    }
    
    public void Tmobileseq.setSimType(String simType) {
        this.simType = simType;
    }
    
    public String Tmobileseq.getProvName() {
        return this.provName;
    }
    
    public void Tmobileseq.setProvName(String provName) {
        this.provName = provName;
    }
    
    public String Tmobileseq.getAreaName() {
        return this.areaName;
    }
    
    public void Tmobileseq.setAreaName(String areaName) {
        this.areaName = areaName;
    }
    
}
