// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tmobileseq_Roo_ToString {
    
    public String Tmobileseq.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("AreaCode: ").append(getAreaCode()).append(", ");
        sb.append("AreaName: ").append(getAreaName()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("ProvCode: ").append(getProvCode()).append(", ");
        sb.append("ProvName: ").append(getProvName()).append(", ");
        sb.append("SimType: ").append(getSimType());
        return sb.toString();
    }
    
}
