// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Torder_Roo_JavaBean {
    
    public String Torder.getId() {
        return this.id;
    }
    
    public void Torder.setId(String id) {
        this.id = id;
    }
    
    public String Torder.getBatchcode() {
        return this.batchcode;
    }
    
    public void Torder.setBatchcode(String batchcode) {
        this.batchcode = batchcode;
    }
    
    public String Torder.getLotno() {
        return this.lotno;
    }
    
    public void Torder.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public BigDecimal Torder.getAmt() {
        return this.amt;
    }
    
    public void Torder.setAmt(BigDecimal amt) {
        this.amt = amt;
    }
    
    public BigDecimal Torder.getPaytype() {
        return this.paytype;
    }
    
    public void Torder.setPaytype(BigDecimal paytype) {
        this.paytype = paytype;
    }
    
    public BigDecimal Torder.getOrderstate() {
        return this.orderstate;
    }
    
    public void Torder.setOrderstate(BigDecimal orderstate) {
        this.orderstate = orderstate;
    }
    
    public BigDecimal Torder.getBettype() {
        return this.bettype;
    }
    
    public void Torder.setBettype(BigDecimal bettype) {
        this.bettype = bettype;
    }
    
    public BigDecimal Torder.getPrizestate() {
        return this.prizestate;
    }
    
    public void Torder.setPrizestate(BigDecimal prizestate) {
        this.prizestate = prizestate;
    }
    
    public BigDecimal Torder.getOrderprizeamt() {
        return this.orderprizeamt;
    }
    
    public void Torder.setOrderprizeamt(BigDecimal orderprizeamt) {
        this.orderprizeamt = orderprizeamt;
    }
    
    public String Torder.getWinbasecode() {
        return this.winbasecode;
    }
    
    public void Torder.setWinbasecode(String winbasecode) {
        this.winbasecode = winbasecode;
    }
    
    public BigDecimal Torder.getOrdertype() {
        return this.ordertype;
    }
    
    public void Torder.setOrdertype(BigDecimal ordertype) {
        this.ordertype = ordertype;
    }
    
    public String Torder.getTsubscribeflowno() {
        return this.tsubscribeflowno;
    }
    
    public void Torder.setTsubscribeflowno(String tsubscribeflowno) {
        this.tsubscribeflowno = tsubscribeflowno;
    }
    
    public String Torder.getTlotcaseid() {
        return this.tlotcaseid;
    }
    
    public void Torder.setTlotcaseid(String tlotcaseid) {
        this.tlotcaseid = tlotcaseid;
    }
    
    public Date Torder.getCreatetime() {
        return this.createtime;
    }
    
    public void Torder.setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    public String Torder.getUserno() {
        return this.userno;
    }
    
    public void Torder.setUserno(String userno) {
        this.userno = userno;
    }
    
    public String Torder.getBuyuserno() {
        return this.buyuserno;
    }
    
    public void Torder.setBuyuserno(String buyuserno) {
        this.buyuserno = buyuserno;
    }
    
    public String Torder.getMemo() {
        return this.memo;
    }
    
    public void Torder.setMemo(String memo) {
        this.memo = memo;
    }
    
    public String Torder.getSubaccount() {
        return this.subaccount;
    }
    
    public void Torder.setSubaccount(String subaccount) {
        this.subaccount = subaccount;
    }
    
    public BigDecimal Torder.getBetnum() {
        return this.betnum;
    }
    
    public void Torder.setBetnum(BigDecimal betnum) {
        this.betnum = betnum;
    }
    
    public String Torder.getBetcode() {
        return this.betcode;
    }
    
    public void Torder.setBetcode(String betcode) {
        this.betcode = betcode;
    }
    
    public String Torder.getBody() {
        return this.body;
    }
    
    public void Torder.setBody(String body) {
        this.body = body;
    }
    
    public BigDecimal Torder.getInstate() {
        return this.instate;
    }
    
    public void Torder.setInstate(BigDecimal instate) {
        this.instate = instate;
    }
    
    public String Torder.getAgencyno() {
        return this.agencyno;
    }
    
    public void Torder.setAgencyno(String agencyno) {
        this.agencyno = agencyno;
    }
    
    public BigDecimal Torder.getPaystate() {
        return this.paystate;
    }
    
    public void Torder.setPaystate(BigDecimal paystate) {
        this.paystate = paystate;
    }
    
    public String Torder.getSubchannel() {
        return this.subchannel;
    }
    
    public void Torder.setSubchannel(String subchannel) {
        this.subchannel = subchannel;
    }
    
}
