// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Torder;
import java.lang.String;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect Torder_Roo_Finder {
    
    public static TypedQuery<Torder> Torder.findTordersByUserno(String userno) {
        if (userno == null || userno.length() == 0) throw new IllegalArgumentException("The userno argument is required");
        EntityManager em = Torder.entityManager();
        TypedQuery<Torder> q = em.createQuery("SELECT o FROM Torder AS o WHERE o.userno = :userno", Torder.class);
        q.setParameter("userno", userno);
        return q;
    }
    
}
