// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Torderform_Roo_ToString {
    
    public String Torderform.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Flowno: ").append(getFlowno()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Orderid: ").append(getOrderid()).append(", ");
        sb.append("Type: ").append(getType());
        return sb.toString();
    }
    
}
