// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Torder_Roo_ToString {
    
    public String Torder.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Agencyno: ").append(getAgencyno()).append(", ");
        sb.append("Amt: ").append(getAmt()).append(", ");
        sb.append("Batchcode: ").append(getBatchcode()).append(", ");
        sb.append("Betcode: ").append(getBetcode()).append(", ");
        sb.append("Betnum: ").append(getBetnum()).append(", ");
        sb.append("Bettype: ").append(getBettype()).append(", ");
        sb.append("Body: ").append(getBody()).append(", ");
        sb.append("Buyuserno: ").append(getBuyuserno()).append(", ");
        sb.append("Createtime: ").append(getCreatetime()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Instate: ").append(getInstate()).append(", ");
        sb.append("Lotno: ").append(getLotno()).append(", ");
        sb.append("Memo: ").append(getMemo()).append(", ");
        sb.append("Orderprizeamt: ").append(getOrderprizeamt()).append(", ");
        sb.append("Orderstate: ").append(getOrderstate()).append(", ");
        sb.append("Ordertype: ").append(getOrdertype()).append(", ");
        sb.append("Paystate: ").append(getPaystate()).append(", ");
        sb.append("Paytype: ").append(getPaytype()).append(", ");
        sb.append("Prizestate: ").append(getPrizestate()).append(", ");
        sb.append("Subaccount: ").append(getSubaccount()).append(", ");
        sb.append("SubaccountType: ").append(getSubaccountType()).append(", ");
        sb.append("Subchannel: ").append(getSubchannel()).append(", ");
        sb.append("Tlotcaseid: ").append(getTlotcaseid()).append(", ");
        sb.append("Tsubscribeflowno: ").append(getTsubscribeflowno()).append(", ");
        sb.append("Userno: ").append(getUserno()).append(", ");
        sb.append("Winbasecode: ").append(getWinbasecode());
        return sb.toString();
    }
    
}
