// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect TorgAccount_Roo_ToString {
    
    public String TorgAccount.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("AccountId: ").append(getAccountId()).append(", ");
        sb.append("BranchId: ").append(getBranchId()).append(", ");
        sb.append("Email: ").append(getEmail()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Info: ").append(getInfo()).append(", ");
        sb.append("LogTime: ").append(getLogTime()).append(", ");
        sb.append("Mobile: ").append(getMobile()).append(", ");
        sb.append("PassWord: ").append(getPassWord()).append(", ");
        sb.append("Prestr: ").append(getPrestr()).append(", ");
        sb.append("RealName: ").append(getRealName()).append(", ");
        sb.append("RegTime: ").append(getRegTime()).append(", ");
        sb.append("Status: ").append(getStatus()).append(", ");
        sb.append("UserName: ").append(getUserName());
        return sb.toString();
    }
    
}
