// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.TorgAccount;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect TorgAccount_Roo_Json {
    
    public String TorgAccount.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static TorgAccount TorgAccount.fromJsonToTorgAccount(String json) {
        return new JSONDeserializer<TorgAccount>().use(null, TorgAccount.class).deserialize(json);
    }
    
    public static String TorgAccount.toJsonArray(Collection<TorgAccount> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<TorgAccount> TorgAccount.fromJsonArrayToTorgAccounts(String json) {
        return new JSONDeserializer<List<TorgAccount>>().use(null, ArrayList.class).use("values", TorgAccount.class).deserialize(json);
    }
    
}
