// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;

privileged aspect Tpermission_Roo_JavaBean {
    
    public BigDecimal Tpermission.getId() {
        return this.id;
    }
    
    public void Tpermission.setId(BigDecimal id) {
        this.id = id;
    }
    
    public BigDecimal Tpermission.getMenuinid() {
        return this.menuinid;
    }
    
    public void Tpermission.setMenuinid(BigDecimal menuinid) {
        this.menuinid = menuinid;
    }
    
    public String Tpermission.getUserid() {
        return this.userid;
    }
    
    public void Tpermission.setUserid(String userid) {
        this.userid = userid;
    }
    
    public BigDecimal Tpermission.getState() {
        return this.state;
    }
    
    public void Tpermission.setState(BigDecimal state) {
        this.state = state;
    }
    
}
