// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tpermission_Roo_ToString {
    
    public String Tpermission.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Menuinid: ").append(getMenuinid()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("Userid: ").append(getUserid());
        return sb.toString();
    }
    
}
