// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tplataccount_Roo_ToString {
    
    public String Tplataccount.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Agencyno: ").append(getAgencyno()).append(", ");
        sb.append("Agentno: ").append(getAgentno()).append(", ");
        sb.append("Earnamt: ").append(getEarnamt()).append(", ");
        sb.append("Lastearnamt: ").append(getLastearnamt()).append(", ");
        sb.append("Lastpayamt: ").append(getLastpayamt()).append(", ");
        sb.append("Laststltime: ").append(getLaststltime()).append(", ");
        sb.append("Mac: ").append(getMac()).append(", ");
        sb.append("Modtime: ").append(getModtime()).append(", ");
        sb.append("Payamt: ").append(getPayamt()).append(", ");
        sb.append("Regtime: ").append(getRegtime()).append(", ");
        sb.append("Totalearnamt: ").append(getTotalearnamt()).append(", ");
        sb.append("Totalpayamt: ").append(getTotalpayamt()).append(", ");
        sb.append("Type: ").append(getType());
        return sb.toString();
    }
    
}
