// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tsubaccount;
import java.math.BigDecimal;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Tsubaccount_Roo_Entity {
    
    declare @type: Tsubaccount: @Entity;
    
    declare @type: Tsubaccount: @Table(name = "TSUBACCOUNT", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Tsubaccount.entityManager;
    
    @Transactional
    public void Tsubaccount.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Tsubaccount.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Tsubaccount attached = Tsubaccount.findTsubaccount(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Tsubaccount.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Tsubaccount.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Tsubaccount Tsubaccount.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Tsubaccount merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Tsubaccount.entityManager() {
        EntityManager em = new Tsubaccount().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Tsubaccount.countTsubaccounts() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Tsubaccount o", Long.class).getSingleResult();
    }
    
    public static List<Tsubaccount> Tsubaccount.findAllTsubaccounts() {
        return entityManager().createQuery("SELECT o FROM Tsubaccount o", Tsubaccount.class).getResultList();
    }
    
    public static Tsubaccount Tsubaccount.findTsubaccount(BigDecimal id) {
        if (id == null) return null;
        return entityManager().find(Tsubaccount.class, id);
    }
    
    public static List<Tsubaccount> Tsubaccount.findTsubaccountEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Tsubaccount o", Tsubaccount.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
