// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Tsubscribe;
import java.lang.String;
import javax.persistence.EntityManager;
import javax.persistence.TypedQuery;

privileged aspect Tsubscribe_Roo_Finder {
    
    public static TypedQuery<Tsubscribe> Tsubscribe.findTsubscribesByUserno(String userno) {
        if (userno == null || userno.length() == 0) throw new IllegalArgumentException("The userno argument is required");
        EntityManager em = Tsubscribe.entityManager();
        TypedQuery<Tsubscribe> q = em.createQuery("SELECT o FROM Tsubscribe AS o WHERE o.userno = :userno", Tsubscribe.class);
        q.setParameter("userno", userno);
        return q;
    }
    
}
