// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;

privileged aspect Ttmctrl_Roo_JavaBean {
    
    public String Ttmctrl.getId() {
        return this.id;
    }
    
    public void Ttmctrl.setId(String id) {
        this.id = id;
    }
    
    public String Ttmctrl.getAgencyno() {
        return this.agencyno;
    }
    
    public void Ttmctrl.setAgencyno(String agencyno) {
        this.agencyno = agencyno;
    }
    
    public String Ttmctrl.getLotno() {
        return this.lotno;
    }
    
    public void Ttmctrl.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public String Ttmctrl.getMachineno() {
        return this.machineno;
    }
    
    public void Ttmctrl.setMachineno(String machineno) {
        this.machineno = machineno;
    }
    
    public BigDecimal Ttmctrl.getMachinestate() {
        return this.machinestate;
    }
    
    public void Ttmctrl.setMachinestate(BigDecimal machinestate) {
        this.machinestate = machinestate;
    }
    
    public BigDecimal Ttmctrl.getTotalcount() {
        return this.totalcount;
    }
    
    public void Ttmctrl.setTotalcount(BigDecimal totalcount) {
        this.totalcount = totalcount;
    }
    
    public BigDecimal Ttmctrl.getTotalamt() {
        return this.totalamt;
    }
    
    public void Ttmctrl.setTotalamt(BigDecimal totalamt) {
        this.totalamt = totalamt;
    }
    
    public BigDecimal Ttmctrl.getMaxcount() {
        return this.maxcount;
    }
    
    public void Ttmctrl.setMaxcount(BigDecimal maxcount) {
        this.maxcount = maxcount;
    }
    
    public BigDecimal Ttmctrl.getMaxamt() {
        return this.maxamt;
    }
    
    public void Ttmctrl.setMaxamt(BigDecimal maxamt) {
        this.maxamt = maxamt;
    }
    
}
