// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Ttransfer_Roo_JavaBean {
    
    public String Ttransfer.getUserno() {
        return this.userno;
    }
    
    public void Ttransfer.setUserno(String userno) {
        this.userno = userno;
    }
    
    public BigDecimal Ttransfer.getState() {
        return this.state;
    }
    
    public void Ttransfer.setState(BigDecimal state) {
        this.state = state;
    }
    
    public Date Ttransfer.getCreatetime() {
        return this.createtime;
    }
    
    public void Ttransfer.setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
    
    public Date Ttransfer.getModifytime() {
        return this.modifytime;
    }
    
    public void Ttransfer.setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
    
}
