// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Ttransfer_Roo_ToString {
    
    public String Ttransfer.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Createtime: ").append(getCreatetime()).append(", ");
        sb.append("Modifytime: ").append(getModifytime()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("Userno: ").append(getUserno());
        return sb.toString();
    }
    
}
