// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Tuserloginfo_Roo_ToString {
    
    public String Tuserloginfo.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Accesstype: ").append(getAccesstype()).append(", ");
        sb.append("Createtime: ").append(getCreatetime()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Random: ").append(getRandom()).append(", ");
        sb.append("Userno: ").append(getUserno());
        return sb.toString();
    }
    
}
