// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Twininfo_Roo_JavaBean {
    
    public String Twininfo.getPlayname() {
        return this.playname;
    }
    
    public void Twininfo.setPlayname(String playname) {
        this.playname = playname;
    }
    
    public String Twininfo.getWinbasecode() {
        return this.winbasecode;
    }
    
    public void Twininfo.setWinbasecode(String winbasecode) {
        this.winbasecode = winbasecode;
    }
    
    public String Twininfo.getWinspecialcode() {
        return this.winspecialcode;
    }
    
    public void Twininfo.setWinspecialcode(String winspecialcode) {
        this.winspecialcode = winspecialcode;
    }
    
    public BigDecimal Twininfo.getActsellamt() {
        return this.actsellamt;
    }
    
    public void Twininfo.setActsellamt(BigDecimal actsellamt) {
        this.actsellamt = actsellamt;
    }
    
    public BigDecimal Twininfo.getValidsellamt() {
        return this.validsellamt;
    }
    
    public void Twininfo.setValidsellamt(BigDecimal validsellamt) {
        this.validsellamt = validsellamt;
    }
    
    public BigDecimal Twininfo.getWingrade() {
        return this.wingrade;
    }
    
    public void Twininfo.setWingrade(BigDecimal wingrade) {
        this.wingrade = wingrade;
    }
    
    public BigDecimal Twininfo.getWinmoney() {
        return this.winmoney;
    }
    
    public void Twininfo.setWinmoney(BigDecimal winmoney) {
        this.winmoney = winmoney;
    }
    
    public BigDecimal Twininfo.getWinnumber() {
        return this.winnumber;
    }
    
    public void Twininfo.setWinnumber(BigDecimal winnumber) {
        this.winnumber = winnumber;
    }
    
    public BigDecimal Twininfo.getForwardamt() {
        return this.forwardamt;
    }
    
    public void Twininfo.setForwardamt(BigDecimal forwardamt) {
        this.forwardamt = forwardamt;
    }
    
    public String Twininfo.getInfo() {
        return this.info;
    }
    
    public void Twininfo.setInfo(String info) {
        this.info = info;
    }
    
    public BigDecimal Twininfo.getState() {
        return this.state;
    }
    
    public void Twininfo.setState(BigDecimal state) {
        this.state = state;
    }
    
    public Date Twininfo.getAgencyopentime() {
        return this.agencyopentime;
    }
    
    public void Twininfo.setAgencyopentime(Date agencyopentime) {
        this.agencyopentime = agencyopentime;
    }
    
}
