// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Twin;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Twin_Roo_Entity {
    
    declare @type: Twin: @Entity;
    
    declare @type: Twin: @Table(name = "TWIN", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Twin.entityManager;
    
    @Transactional
    public void Twin.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Twin attached = Twin.findTwin(this.flowno);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Twin.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Twin.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    public static final EntityManager Twin.entityManager() {
        EntityManager em = new Twin().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Twin.countTwins() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Twin o", Long.class).getSingleResult();
    }
    
    public static List<Twin> Twin.findAllTwins() {
        return entityManager().createQuery("SELECT o FROM Twin o", Twin.class).getResultList();
    }
    
    public static Twin Twin.findTwin(String flowno) {
        if (flowno == null || flowno.length() == 0) return null;
        return entityManager().find(Twin.class, flowno);
    }
    
    public static List<Twin> Twin.findTwinEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Twin o", Twin.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
