// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Twininfo_Roo_ToString {
    
    public String Twininfo.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Actsellamt: ").append(getActsellamt()).append(", ");
        sb.append("Agencyopentime: ").append(getAgencyopentime()).append(", ");
        sb.append("Forwardamt: ").append(getForwardamt()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Info: ").append(getInfo()).append(", ");
        sb.append("Playname: ").append(getPlayname()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("Validsellamt: ").append(getValidsellamt()).append(", ");
        sb.append("Winbasecode: ").append(getWinbasecode()).append(", ");
        sb.append("Wingrade: ").append(getWingrade()).append(", ");
        sb.append("Winmoney: ").append(getWinmoney()).append(", ");
        sb.append("Winnumber: ").append(getWinnumber()).append(", ");
        sb.append("Winspecialcode: ").append(getWinspecialcode());
        return sb.toString();
    }
    
}
