// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.Twininfo;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect Twininfo_Roo_Json {
    
    public String Twininfo.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static Twininfo Twininfo.fromJsonToTwininfo(String json) {
        return new JSONDeserializer<Twininfo>().use(null, Twininfo.class).deserialize(json);
    }
    
    public static String Twininfo.toJsonArray(Collection<Twininfo> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<Twininfo> Twininfo.fromJsonArrayToTwininfoes(String json) {
        return new JSONDeserializer<List<Twininfo>>().use(null, ArrayList.class).use("values", Twininfo.class).deserialize(json);
    }
    
}
