// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import com.ruyicai.mgr.domain.CompositePK;
import com.ruyicai.mgr.domain.Twininfo;
import java.util.List;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect Twininfo_Roo_Entity {
    
    declare @type: Twininfo: @Entity;
    
    declare @type: Twininfo: @Table(name = "TWININFO", schema = "JRTSCH");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager Twininfo.entityManager;
    
    @EmbeddedId
    private CompositePK Twininfo.id;
    
    public CompositePK Twininfo.getId() {
        return this.id;
    }
    
    public void Twininfo.setId(CompositePK id) {
        this.id = id;
    }
    
    @Transactional
    public void Twininfo.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void Twininfo.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            Twininfo attached = Twininfo.findTwininfo(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void Twininfo.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void Twininfo.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public Twininfo Twininfo.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        Twininfo merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager Twininfo.entityManager() {
        EntityManager em = new Twininfo().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long Twininfo.countTwininfoes() {
        return entityManager().createQuery("SELECT COUNT(o) FROM Twininfo o", Long.class).getSingleResult();
    }
    
    public static List<Twininfo> Twininfo.findAllTwininfoes() {
        return entityManager().createQuery("SELECT o FROM Twininfo o", Twininfo.class).getResultList();
    }
    
    public static Twininfo Twininfo.findTwininfo(CompositePK id) {
        if (id == null) return null;
        return entityManager().find(Twininfo.class, id);
    }
    
    public static List<Twininfo> Twininfo.findTwininfoEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM Twininfo o", Twininfo.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
