// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect Txianhao_Roo_JavaBean {
    
    public BigDecimal Txianhao.getId() {
        return this.id;
    }
    
    public void Txianhao.setId(BigDecimal id) {
        this.id = id;
    }
    
    public String Txianhao.getLotno() {
        return this.lotno;
    }
    
    public void Txianhao.setLotno(String lotno) {
        this.lotno = lotno;
    }
    
    public String Txianhao.getAgencyno() {
        return this.agencyno;
    }
    
    public void Txianhao.setAgencyno(String agencyno) {
        this.agencyno = agencyno;
    }
    
    public String Txianhao.getBatchcode() {
        return this.batchcode;
    }
    
    public void Txianhao.setBatchcode(String batchcode) {
        this.batchcode = batchcode;
    }
    
    public Date Txianhao.getUpdatetime() {
        return this.updatetime;
    }
    
    public void Txianhao.setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
    
    public String Txianhao.getBetcode() {
        return this.betcode;
    }
    
    public void Txianhao.setBetcode(String betcode) {
        this.betcode = betcode;
    }
    
    public BigDecimal Txianhao.getCount() {
        return this.count;
    }
    
    public void Txianhao.setCount(BigDecimal count) {
        this.count = count;
    }
    
    public BigDecimal Txianhao.getState() {
        return this.state;
    }
    
    public void Txianhao.setState(BigDecimal state) {
        this.state = state;
    }
    
}
