// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.lang.String;

privileged aspect Txianhao_Roo_ToString {
    
    public String Txianhao.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Agencyno: ").append(getAgencyno()).append(", ");
        sb.append("Batchcode: ").append(getBatchcode()).append(", ");
        sb.append("Betcode: ").append(getBetcode()).append(", ");
        sb.append("Count: ").append(getCount()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Lotno: ").append(getLotno()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("Updatetime: ").append(getUpdatetime());
        return sb.toString();
    }
    
}
