// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain.statis;

import java.lang.String;

privileged aspect Channel_Roo_ToString {
    
    public String Channel.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Bduserid: ").append(getBduserid()).append(", ");
        sb.append("Bz: ").append(getBz()).append(", ");
        sb.append("Charge: ").append(getCharge()).append(", ");
        sb.append("Cjdate: ").append(getCjdate()).append(", ");
        sb.append("Code: ").append(getCode()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Isopen: ").append(getIsopen()).append(", ");
        sb.append("Map: ").append(getMap() == null ? "null" : getMap().size()).append(", ");
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("Regist: ").append(getRegist()).append(", ");
        sb.append("Status: ").append(getStatus()).append(", ");
        sb.append("Tel: ").append(getTel()).append(", ");
        sb.append("Url: ").append(getUrl()).append(", ");
        sb.append("Ywid: ").append(getYwid());
        return sb.toString();
    }
    
}
