// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain.statis;

import java.lang.Double;
import java.lang.Integer;
import java.lang.String;
import java.util.Date;

privileged aspect Channel_Roo_JavaBean {
    
    public Integer Channel.getId() {
        return this.id;
    }
    
    public void Channel.setId(Integer id) {
        this.id = id;
    }
    
    public Integer Channel.getYwid() {
        return this.ywid;
    }
    
    public void Channel.setYwid(Integer ywid) {
        this.ywid = ywid;
    }
    
    public String Channel.getCode() {
        return this.code;
    }
    
    public void Channel.setCode(String code) {
        this.code = code;
    }
    
    public String Channel.getName() {
        return this.name;
    }
    
    public void Channel.setName(String name) {
        this.name = name;
    }
    
    public Integer Channel.getBduserid() {
        return this.bduserid;
    }
    
    public void Channel.setBduserid(Integer bduserid) {
        this.bduserid = bduserid;
    }
    
    public Date Channel.getCjdate() {
        return this.cjdate;
    }
    
    public void Channel.setCjdate(Date cjdate) {
        this.cjdate = cjdate;
    }
    
    public Integer Channel.getStatus() {
        return this.status;
    }
    
    public void Channel.setStatus(Integer status) {
        this.status = status;
    }
    
    public String Channel.getBz() {
        return this.bz;
    }
    
    public void Channel.setBz(String bz) {
        this.bz = bz;
    }
    
    public String Channel.getTel() {
        return this.tel;
    }
    
    public void Channel.setTel(String tel) {
        this.tel = tel;
    }
    
    public String Channel.getUrl() {
        return this.url;
    }
    
    public void Channel.setUrl(String url) {
        this.url = url;
    }
    
    public Integer Channel.getIsopen() {
        return this.isopen;
    }
    
    public void Channel.setIsopen(Integer isopen) {
        this.isopen = isopen;
    }
    
    public Double Channel.getRegist() {
        return this.regist;
    }
    
    public void Channel.setRegist(Double regist) {
        this.regist = regist;
    }
    
    public Double Channel.getCharge() {
        return this.charge;
    }
    
    public void Channel.setCharge(Double charge) {
        this.charge = charge;
    }
    
}
