// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain.statis;

import com.ruyicai.mgr.domain.statis.PvTJ;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PvTJ_Roo_Entity {
    
    declare @type: PvTJ: @Entity;
    
    declare @type: PvTJ: @Table(name = "PVTJ", schema = "JRTSTATIS");
    
    @PersistenceContext(unitName = "persistenceUnit")
    transient EntityManager PvTJ.entityManager;
    
    @Transactional
    public void PvTJ.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional
    public void PvTJ.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            PvTJ attached = PvTJ.findPvTJ(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional
    public void PvTJ.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional
    public void PvTJ.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional
    public PvTJ PvTJ.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        PvTJ merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager PvTJ.entityManager() {
        EntityManager em = new PvTJ().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long PvTJ.countPvTJs() {
        return entityManager().createQuery("SELECT COUNT(o) FROM PvTJ o", Long.class).getSingleResult();
    }
    
    public static List<PvTJ> PvTJ.findAllPvTJs() {
        return entityManager().createQuery("SELECT o FROM PvTJ o", PvTJ.class).getResultList();
    }
    
    public static PvTJ PvTJ.findPvTJ(int id) {
        return entityManager().find(PvTJ.class, id);
    }
    
    public static List<PvTJ> PvTJ.findPvTJEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM PvTJ o", PvTJ.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
