// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain.statis;

import java.lang.String;

privileged aspect TCooperat_Roo_ToString {
    
    public String TCooperat.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("ChannlId: ").append(getChannlId()).append(", ");
        sb.append("CooperatType: ").append(getCooperatType()).append(", ");
        sb.append("Count: ").append(getCount()).append(", ");
        sb.append("CountType: ").append(getCountType()).append(", ");
        sb.append("Id: ").append(getId());
        return sb.toString();
    }
    
}
