// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain.statis;

import java.lang.Double;
import java.lang.Long;
import java.lang.String;

privileged aspect TCooperat_Roo_JavaBean {
    
    public Long TCooperat.getId() {
        return this.id;
    }
    
    public void TCooperat.setId(Long id) {
        this.id = id;
    }
    
    public String TCooperat.getChannlId() {
        return this.channlId;
    }
    
    public void TCooperat.setChannlId(String channlId) {
        this.channlId = channlId;
    }
    
    public String TCooperat.getCooperatType() {
        return this.cooperatType;
    }
    
    public void TCooperat.setCooperatType(String cooperatType) {
        this.cooperatType = cooperatType;
    }
    
    public String TCooperat.getCountType() {
        return this.countType;
    }
    
    public void TCooperat.setCountType(String countType) {
        this.countType = countType;
    }
    
    public Double TCooperat.getCount() {
        return this.count;
    }
    
    public void TCooperat.setCount(Double count) {
        this.count = count;
    }
    
}
