// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain.statis;

import java.lang.String;

privileged aspect User_Roo_ToString {
    
    public String User.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Bz: ").append(getBz()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("Pass: ").append(getPass()).append(", ");
        sb.append("Realname: ").append(getRealname()).append(", ");
        sb.append("Regdate: ").append(getRegdate()).append(", ");
        sb.append("Roleid: ").append(getRoleid()).append(", ");
        sb.append("Status: ").append(getStatus()).append(", ");
        sb.append("Tel: ").append(getTel());
        return sb.toString();
    }
    
}
