// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain.statis;

import java.lang.Integer;
import java.lang.String;
import java.util.Date;

privileged aspect Yw_Roo_JavaBean {
    
    public int Yw.getId() {
        return this.id;
    }
    
    public void Yw.setId(int id) {
        this.id = id;
    }
    
    public String Yw.getCode() {
        return this.code;
    }
    
    public void Yw.setCode(String code) {
        this.code = code;
    }
    
    public String Yw.getName() {
        return this.name;
    }
    
    public void Yw.setName(String name) {
        this.name = name;
    }
    
    public int Yw.getBduserid() {
        return this.bduserid;
    }
    
    public void Yw.setBduserid(int bduserid) {
        this.bduserid = bduserid;
    }
    
    public Date Yw.getCjdate() {
        return this.cjdate;
    }
    
    public void Yw.setCjdate(Date cjdate) {
        this.cjdate = cjdate;
    }
    
    public Integer Yw.getStatus() {
        return this.status;
    }
    
    public void Yw.setStatus(Integer status) {
        this.status = status;
    }
    
    public String Yw.getBz() {
        return this.bz;
    }
    
    public void Yw.setBz(String bz) {
        this.bz = bz;
    }
    
}
