// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.domain;

import java.io.Serializable;

privileged aspect TlottypePK_Roo_Serializable {
    
    declare parents: TlottypePK implements Serializable;
    
    private static final long TlottypePK.serialVersionUID = 1L;
    
}
