// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.controller.dto;

import java.lang.String;

privileged aspect AccountDto_Roo_ToString {
    
    public String AccountDto.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Logic_code: ").append(getLogic_code()).append(", ");
        sb.append("Name: ").append(getName()).append(", ");
        sb.append("Random_num: ").append(getRandom_num());
        return sb.toString();
    }
    
}
