// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.controller.dto;

import com.ruyicai.mgr.controller.dto.AccountDto;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect AccountDto_Roo_Json {
    
    public String AccountDto.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static AccountDto AccountDto.fromJsonToAccountDto(String json) {
        return new JSONDeserializer<AccountDto>().use(null, AccountDto.class).deserialize(json);
    }
    
    public static String AccountDto.toJsonArray(Collection<AccountDto> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<AccountDto> AccountDto.fromJsonArrayToAccountDtoes(String json) {
        return new JSONDeserializer<List<AccountDto>>().use(null, ArrayList.class).use("values", AccountDto.class).deserialize(json);
    }
    
}
