// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.controller.dto;

import java.lang.String;

privileged aspect AccountDto_Roo_JavaBean {
    
    public String AccountDto.getName() {
        return this.name;
    }
    
    public void AccountDto.setName(String name) {
        this.name = name;
    }
    
    public String AccountDto.getRandom_num() {
        return this.random_num;
    }
    
    public void AccountDto.setRandom_num(String random_num) {
        this.random_num = random_num;
    }
    
    public String AccountDto.getLogic_code() {
        return this.logic_code;
    }
    
    public void AccountDto.setLogic_code(String logic_code) {
        this.logic_code = logic_code;
    }
    
}
