// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.controller.dto;

import com.ruyicai.mgr.controller.dto.BigUserTransactionDto;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect BigUserTransactionDto_Roo_Json {
    
    public String BigUserTransactionDto.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static BigUserTransactionDto BigUserTransactionDto.fromJsonToBigUserTransactionDto(String json) {
        return new JSONDeserializer<BigUserTransactionDto>().use(null, BigUserTransactionDto.class).deserialize(json);
    }
    
    public static String BigUserTransactionDto.toJsonArray(Collection<BigUserTransactionDto> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<BigUserTransactionDto> BigUserTransactionDto.fromJsonArrayToBigUserTransactionDtoes(String json) {
        return new JSONDeserializer<List<BigUserTransactionDto>>().use(null, ArrayList.class).use("values", BigUserTransactionDto.class).deserialize(json);
    }
    
}
