// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.controller.dto;

import java.lang.String;
import java.math.BigDecimal;
import java.util.Date;

privileged aspect BigUserTransactionDto_Roo_JavaBean {
    
    public String BigUserTransactionDto.getId() {
        return this.id;
    }
    
    public void BigUserTransactionDto.setId(String id) {
        this.id = id;
    }
    
    public String BigUserTransactionDto.getType() {
        return this.type;
    }
    
    public void BigUserTransactionDto.setType(String type) {
        this.type = type;
    }
    
    public Date BigUserTransactionDto.getPlattime() {
        return this.plattime;
    }
    
    public void BigUserTransactionDto.setPlattime(Date plattime) {
        this.plattime = plattime;
    }
    
    public BigDecimal BigUserTransactionDto.getAmt() {
        return this.amt;
    }
    
    public void BigUserTransactionDto.setAmt(BigDecimal amt) {
        this.amt = amt;
    }
    
    public String BigUserTransactionDto.getState() {
        return this.state;
    }
    
    public void BigUserTransactionDto.setState(String state) {
        this.state = state;
    }
    
    public String BigUserTransactionDto.getAgencyno() {
        return this.agencyno;
    }
    
    public void BigUserTransactionDto.setAgencyno(String agencyno) {
        this.agencyno = agencyno;
    }
    
    public String BigUserTransactionDto.getAgencyname() {
        return this.agencyname;
    }
    
    public void BigUserTransactionDto.setAgencyname(String agencyname) {
        this.agencyname = agencyname;
    }
    
    public String BigUserTransactionDto.getTelephone() {
        return this.telephone;
    }
    
    public void BigUserTransactionDto.setTelephone(String telephone) {
        this.telephone = telephone;
    }
    
}
