// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.controller.dto;

import com.ruyicai.mgr.controller.dto.CaseLotCelebrityDTO;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect CaseLotCelebrityDTO_Roo_Json {
    
    public String CaseLotCelebrityDTO.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static CaseLotCelebrityDTO CaseLotCelebrityDTO.fromJsonToCaseLotCelebrityDTO(String json) {
        return new JSONDeserializer<CaseLotCelebrityDTO>().use(null, CaseLotCelebrityDTO.class).deserialize(json);
    }
    
    public static String CaseLotCelebrityDTO.toJsonArray(Collection<CaseLotCelebrityDTO> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<CaseLotCelebrityDTO> CaseLotCelebrityDTO.fromJsonArrayToCaseLoes(String json) {
        return new JSONDeserializer<List<CaseLotCelebrityDTO>>().use(null, ArrayList.class).use("values", CaseLotCelebrityDTO.class).deserialize(json);
    }
    
}
