// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.mysql.domain;

import java.lang.Object;
import java.lang.String;
import java.math.BigDecimal;
import javax.persistence.Embeddable;

privileged aspect MatchesCompositePK_Roo_Identifier {
    
    declare @type: MatchesCompositePK: @Embeddable;
    
    public MatchesCompositePK.new(BigDecimal type, String day, BigDecimal weekid, String teamid) {
        super();
        this.type = type;
        this.day = day;
        this.weekid = weekid;
        this.teamid = teamid;
    }

    private MatchesCompositePK.new() {
        super();
    }

    public BigDecimal MatchesCompositePK.getType() {
        return this.type;
    }
    
    public String MatchesCompositePK.getDay() {
        return this.day;
    }
    
    public BigDecimal MatchesCompositePK.getWeekid() {
        return this.weekid;
    }
    
    public String MatchesCompositePK.getTeamid() {
        return this.teamid;
    }
    
    public boolean MatchesCompositePK.equals(Object obj) {
        if (this == obj) return true;
        if (obj == null) return false;
        if (!(obj instanceof MatchesCompositePK)) return false;
        MatchesCompositePK other = (MatchesCompositePK) obj;
        if (type == null) {
            if (other.type != null) return false;
        } else if (!type.equals(other.type)) return false;
        if (day == null) {
            if (other.day != null) return false;
        } else if (!day.equals(other.day)) return false;
        if (weekid == null) {
            if (other.weekid != null) return false;
        } else if (!weekid.equals(other.weekid)) return false;
        if (teamid == null) {
            if (other.teamid != null) return false;
        } else if (!teamid.equals(other.teamid)) return false;
        return true;
    }
    
    public int MatchesCompositePK.hashCode() {
        final int prime = 31;
        int result = 17;
        result = prime * result + (type == null ? 0 : type.hashCode());
        result = prime * result + (day == null ? 0 : day.hashCode());
        result = prime * result + (weekid == null ? 0 : weekid.hashCode());
        result = prime * result + (teamid == null ? 0 : teamid.hashCode());
        return result;
    }
    
}
