// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.mysql.domain;

import com.ruyicai.mgr.mysql.domain.MatchesCompositePK;
import flexjson.JSONDeserializer;
import flexjson.JSONSerializer;
import java.lang.String;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;

privileged aspect MatchesCompositePK_Roo_Json {
    
    public String MatchesCompositePK.toJson() {
        return new JSONSerializer().exclude("*.class").serialize(this);
    }
    
    public static MatchesCompositePK MatchesCompositePK.fromJsonToMatchesCompositePK(String json) {
        return new JSONDeserializer<MatchesCompositePK>().use(null, MatchesCompositePK.class).deserialize(json);
    }
    
    public static String MatchesCompositePK.toJsonArray(Collection<MatchesCompositePK> collection) {
        return new JSONSerializer().exclude("*.class").serialize(collection);
    }
    
    public static Collection<MatchesCompositePK> MatchesCompositePK.fromJsonArrayToMatchesCompositePKs(String json) {
        return new JSONDeserializer<List<MatchesCompositePK>>().use(null, ArrayList.class).use("values", MatchesCompositePK.class).deserialize(json);
    }
    
}
