// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.mysql.domain;

import java.lang.String;

privileged aspect TjingcaigyjMatch_Roo_ToString {
    
    public String TjingcaigyjMatch.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Award: ").append(getAward()).append(", ");
        sb.append("Id: ").append(getId()).append(", ");
        sb.append("Number: ").append(getNumber()).append(", ");
        sb.append("PopularityRating: ").append(getPopularityRating()).append(", ");
        sb.append("Probability: ").append(getProbability()).append(", ");
        sb.append("Saishi: ").append(getSaishi()).append(", ");
        sb.append("State: ").append(getState()).append(", ");
        sb.append("Team: ").append(getTeam()).append(", ");
        sb.append("Type: ").append(getType());
        return sb.toString();
    }
    
}
