// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.mysql.domain;

import com.ruyicai.mgr.mysql.domain.TjingcaiResult;
import java.lang.String;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Table;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TjingcaiResult_Roo_Entity {
    
    declare @type: TjingcaiResult: @Entity;
    
    declare @type: TjingcaiResult: @Table(name = "tjingcairesult");
    
    @PersistenceContext(unitName = "clientPersistenceUnit")
    transient EntityManager TjingcaiResult.entityManager;
    
    @Transactional("newsTransactionManager")
    public void TjingcaiResult.persist() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.persist(this);
    }
    
    @Transactional("newsTransactionManager")
    public void TjingcaiResult.remove() {
        if (this.entityManager == null) this.entityManager = entityManager();
        if (this.entityManager.contains(this)) {
            this.entityManager.remove(this);
        } else {
            TjingcaiResult attached = TjingcaiResult.findTjingcaiResult(this.id);
            this.entityManager.remove(attached);
        }
    }
    
    @Transactional("newsTransactionManager")
    public void TjingcaiResult.flush() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.flush();
    }
    
    @Transactional("newsTransactionManager")
    public void TjingcaiResult.clear() {
        if (this.entityManager == null) this.entityManager = entityManager();
        this.entityManager.clear();
    }
    
    @Transactional("newsTransactionManager")
    public TjingcaiResult TjingcaiResult.merge() {
        if (this.entityManager == null) this.entityManager = entityManager();
        TjingcaiResult merged = this.entityManager.merge(this);
        this.entityManager.flush();
        return merged;
    }
    
    public static final EntityManager TjingcaiResult.entityManager() {
        EntityManager em = new TjingcaiResult().entityManager;
        if (em == null) throw new IllegalStateException("Entity manager has not been injected (is the Spring Aspects JAR configured as an AJC/AJDT aspects library?)");
        return em;
    }
    
    public static long TjingcaiResult.countTjingcaiResults() {
        return entityManager().createQuery("SELECT COUNT(o) FROM TjingcaiResult o", Long.class).getSingleResult();
    }
    
    public static List<TjingcaiResult> TjingcaiResult.findAllTjingcaiResults() {
        return entityManager().createQuery("SELECT o FROM TjingcaiResult o", TjingcaiResult.class).getResultList();
    }
    
    public static TjingcaiResult TjingcaiResult.findTjingcaiResult(String id) {
        if (id == null || id.length() == 0) return null;
        return entityManager().find(TjingcaiResult.class, id);
    }
    
    public static List<TjingcaiResult> TjingcaiResult.findTjingcaiResultEntries(int firstResult, int maxResults) {
        return entityManager().createQuery("SELECT o FROM TjingcaiResult o", TjingcaiResult.class).setFirstResult(firstResult).setMaxResults(maxResults).getResultList();
    }
    
}
