// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.ruyicai.mgr.mysql.domain;

import java.io.Serializable;

privileged aspect MatchesCompositePK_Roo_Serializable {
    
    declare parents: MatchesCompositePK implements Serializable;
    
    private static final long MatchesCompositePK.serialVersionUID = 1L;
    
}
